server:
  port: 8095

spring:
  logging:
    level:
      org.springframework.cloud.config: DEBUG
      org.springframework.boot.context.config: DEBUG
      io.github.resilience4j: DEBUG
      io.github.resilience4j.retry: DEBUG
      io.github.resilience4j.circuitbreaker: DEBUG
      io.github.resilience4j.ratelimiter: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    circuitbreakers:
      enabled: true

  endpoint:
    health:
      show-details: always     
        
resilience4j:
  circuitbreaker:
    instances:
      productServiceCB:
        registerHealthIndicator: false
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED # Use count-based sliding window
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitRefreshPeriod: 5s
        limitForPeriod: 1
        timeoutDuration: 1s
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 10s
    instances:
      inventoryRetry:
        baseConfig: default
        waitDuration: 200ms
