server:
  port: 8095

spring:
  logging:
    level:
      org.springframework.cloud.config: DEBUG
      org.springframework.boot.context.config: DEBUG
      io.github.resilience4j: DEBUG
      io.github.resilience4j.retry: DEBUG
      io.github.resilience4j.circuitbreaker: DEBUG
      io.github.resilience4j.ratelimiter: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

      
  

  endpoint:
    health:
      show-details: always     
        
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1 # CB wraps RateLimiter
    instances:
      productServiceCB:
        registerHealthIndicator: false
        slidingWindowSize: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 1
        recordExceptions:
          - java.lang.Exception
          - io.github.resilience4j.ratelimiter.RequestNotPermitted

  ratelimiter:
    rate-limiter-aspect-order: 2
    instances:
      inventoryRateLimiter:
        limitForPeriod: 2      # har 10s mein max 2 requests
        limitRefreshPeriod: 10s
        timeoutDuration: 2s

  retry:
    instances:
      inventoryRetry:
        maxRetryAttempts: 4    # total 3 retries
        waitDuration: 2s       # 1s gap between retries
        retryExceptions:
          - java.lang.Exception
